// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

/*

Actions Résultat attendu


Accéder à l’application Jpetstore et se 
connecter en tant que j2ee/j2ee
L’utilisateur « ABC » est bien connecté 
(apparition d’un message de bienvenu 
et du lien « Sign out »)


===
Sélectionner la catégorie Fish 
Affichage de la liste des produit 
disponible pour la catégorie Fish
==
Sélectionner le produit de votre choix 
et l’ajouter à votre panier

Affichage du panier

==
Procéder au paiement (Proceed to 
Checkout + Continue)

Affichage des informations de 
l’acheteur (ex : First name = ABC)
Confirmer la commande La commande est confirmée


 */
public class PetstoreTest2 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.gecko.driver", "C:\\Users\\Formation\\Downloads\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("https://petstore.octoperf.com/actions/Account.action?signonForm=");
   // driver.manage().window().fullscreen();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

    driver.findElement(By.xpath("//*[@name='username']")).sendKeys("j2ee");
    driver.findElement(By.xpath("//*[@id=\"Catalog\"]/form/p[2]/input[2]")).clear();
    driver.findElement(By.xpath("//*[@id=\"Catalog\"]/form/p[2]/input[2]")).sendKeys("j2ee");
    
    driver.findElement(By.xpath("//*[@id=\"Catalog\"]/form/input")).click();
    
    /*
    driver.findElement(By.cssSelector("#menu-item-8 > a")).click();
    driver.findElement(By.cssSelector("#menu-item-898 > a")).click();
    driver.findElement(By.cssSelector("#menu-item-103 > a")).click();
    
    assertThat(driver.findElement(By.cssSelector(".entry-title")).getText(), is("LIENS UTILES"));
     */
    
    assertTrue("afficher Welcome ", 
    		driver.findElement(By.xpath("//*[@id=\"WelcomeContent\"]")).getText().contains("Welcome"));
    assertTrue("afficher Sign out ", 
    		driver.findElement(By.xpath("//a[.='Sign Out']")).getText().contains("Sign Out"));
    
    /**
     * <a href="/actions/Catalog.action?viewCategory=&amp;categoryId=FISH"><img src="../images/fish_icon.gif"></a>
     */
    driver.findElement(By.xpath("//a[contains(@href,'FISH')]")).click();
    
    driver.findElement(By.xpath("//a[.='FI-SW-01']")).click();
    
    
    driver.findElement(By.xpath("//a[.='Add to Cart']")).click();
    
    // Proceed to Checkout
    driver.findElement(By.xpath("//a[.='Proceed to Checkout']")).click();
    
    driver.findElement(By.xpath("//input[@value='Continue']")).click();
    
    driver.findElement(By.xpath("//a[.='Confirm']")).click();
    
    System.out.println("end");
  }
}
